version: '2'

services:
  postgres:
    image: postgres:12.3
    container_name: postgres-12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
